// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(OMAContext))]
    partial class OMAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Core.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Main St",
                            City = "New York",
                            Country = "US",
                            CustomerId = 1,
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "456 Main St",
                            City = "Los Angeles",
                            Country = "US",
                            CustomerId = 2,
                            State = "CA"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "1 Somewhere St",
                            City = "Someplace",
                            Country = "US",
                            CustomerId = 3,
                            State = "CA"
                        });
                });

            modelBuilder.Entity("Core.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "1234567890",
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "1111111111",
                            Email = "jane.doe@email.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "2222222222",
                            Email = "bob@email.com",
                            FirstName = "Bob",
                            IsDeleted = false,
                            LastName = "Builder"
                        });
                });

            modelBuilder.Entity("Core.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDelivery")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DepositAmount = 50m,
                            Description = "order 123",
                            IsDeleted = false,
                            IsDelivery = true,
                            OrderDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalAmount = 100m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            DepositAmount = 50m,
                            Description = "order 456",
                            IsDeleted = false,
                            IsDelivery = true,
                            OrderDate = new DateTime(2021, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 100m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 1,
                            DepositAmount = 99m,
                            Description = "order 321",
                            IsDeleted = false,
                            IsDelivery = true,
                            OrderDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalAmount = 200m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            DepositAmount = 99m,
                            Description = "order 654",
                            IsDeleted = false,
                            IsDelivery = true,
                            OrderDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TotalAmount = 200m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 1,
                            DepositAmount = 88m,
                            Description = "order 111",
                            IsDeleted = false,
                            IsDelivery = true,
                            OrderDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            TotalAmount = 200m
                        });
                });

            modelBuilder.Entity("Core.Entities.Address", b =>
                {
                    b.HasOne("Core.Entities.Customer", null)
                        .WithOne("Address")
                        .HasForeignKey("Core.Entities.Address", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Order", b =>
                {
                    b.HasOne("Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Core.Entities.Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
